name: build

on:
    push:
        branches: ["release"]

jobs:
    windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v1
          with:
            submodules: true
        - name: win64-vstudio-release
          run:  python fips build win64-vstudio-release
        - uses: actions/upload-artifact@v2
          with:
            path: fips-deploy/sokol-tools/win64-vstudio-release/sokol-shdc.exe
            name: win32
    mac:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v1
          with:
            submodules: true
        - name: osx-make-release
          run:  python fips build osx-make-release
        - uses: actions/upload-artifact@v2
          with:
            path: fips-deploy/sokol-tools/osx-make-release/sokol-shdc
            name: osx
    linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          with:
            submodules: true
        - name: linux-make-release
          run:  python fips build linux-make-release
        - uses: actions/upload-artifact@v2
          with:
            path: fips-deploy/sokol-tools/linux-make-release/sokol-shdc
            name: linux

