name: build

on:
    push:
        branches: ["release"]

jobs:
    windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v1
          with:
            submodules: true
        - name: win64-vstudio-release
          run:  python fips build win64-vstudio-release
        - uses: actions/upload-artifact@v2
          with:
            path: D:/a/sokol-tools/fips-deploy/sokol-tools/win64-vstudio-release/sokol-shdc.exe
            name: win32
    mac:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v1
          with:
            submodules: true
        - name: osx-make-release
          run:  python fips build osx-make-release
        - uses: actions/upload-artifact@v2
          with:
            path: /Users/runner/work/sokol-tools/fips-deploy/sokol-tools/osx-make-release/sokol-shdc
            name: osx
    linux:
        runs-on: ubuntu-latest
        container:
            image: alpine:latest
        steps:
        - name: Prepare environment
          run: apk add build-base git vim python2 cmake
        - uses: actions/checkout@v1
          with:
            submodules: true
        - name: linux-make-release
          run: |
            python fips build linux-make-release
            strip /__w/sokol-tools/fips-deploy/sokol-tools/linux-make-release/sokol-shdc
        - uses: actions/upload-artifact@v2
          with:
            path: /__w/sokol-tools/fips-deploy/sokol-tools/linux-make-release/sokol-shdc
            name: linux
    publish:
        runs-on: ubuntu-latest
        needs: [windows, mac, linux]
        steps:
        - uses: actions/download-artifact@v2
        - name: rename
          run: |
            mv linux/sokol-shdc sokol-shdc-linux
            mv osx/sokol-shdc sokol-shdc-osx
            mv win32/sokol-shdc.exe sokol-shdc-win32.exe
            rm -rf linux osx win32
        - name: publish
          uses: marvinpinto/action-automatic-releases@v1.2.1
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: build-${{ github.sha }}
            files: *

